Repository shu8/fellowhub, pull requests merged in 2020-07, with the labels that each got.

#3 Add Discord guild members retrieval snippet
  discord-bot/index.js
Labels: halfway-hackathon

#1 Fetch and store Fellow skills
  github-api/allUsers.json
  github-api/allUsersSkills.json
  github-api/fetch-skills.js
  github-api/fetcher.js
  github-api/usernames.json
Labels: halfway-hackathon

#5 Add /events endpoint to get events from Fellowship GCal
  aws-backend/amplify/backend/api/fellowbookapi/api-params.json
  aws-backend/amplify/backend/api/fellowbookapi/fellowbookapi-cloudformation-template.json
  aws-backend/amplify/backend/backend-config.json
  aws-backend/amplify/backend/function/calendarendpoint/amplify.state
  aws-backend/amplify/backend/function/calendarendpoint/calendarendpoint-cloudformation-template.json
  aws-backend/amplify/backend/function/calendarendpoint/function-parameters.json
  aws-backend/amplify/backend/function/calendarendpoint/parameters.json
  aws-backend/amplify/backend/function/calendarendpoint/src/app.js
  aws-backend/amplify/backend/function/calendarendpoint/src/event.json
  aws-backend/amplify/backend/function/calendarendpoint/src/index.js
  aws-backend/amplify/backend/function/calendarendpoint/src/package-lock.json
  aws-backend/amplify/backend/function/calendarendpoint/src/package.json
Labels: halfway-hackathon

#8 Add support for fetching multiple standups for a user
  aws-backend/amplify/backend/function/standupendpoint/src/app.js
  aws-backend/amplify/backend/function/standupendpoint/standupendpoint-cloudformation-template.json
Labels: halfway-hackathon

#10 Add fellow skill retrieval from repo languages
  github-api/supplementFellowSkills.js
Labels: data scraping, halfway-hackathon

#12 Add data on recent pull requests and issues to /fellow endpoint
  aws-backend/amplify/backend/function/fellowendpoint/fellowendpoint-cloudformation-template.json
  aws-backend/amplify/backend/function/fellowendpoint/src/app.js
  aws-backend/amplify/backend/function/fellowendpoint/src/package-lock.json
  aws-backend/amplify/backend/function/fellowendpoint/src/package.json
  aws-backend/amplify/backend/function/standupendpoint/standupendpoint-cloudformation-template.json
Labels: backend, halfway-hackathon

#23 Webapp home
  web/package-lock.json
  web/package.json
  web/src/App.css
  web/src/App.js
  web/src/Components/Header.js
  web/src/Components/Header.jsx
  web/src/Components/Pods.js
  web/src/Components/Profile.jsx
  web/src/Components/Projects.js
  web/src/Components/SimpleAvatar.js
  web/src/Components/index.js
  web/src/Pages/Events.js
  web/src/Pages/Fellows.js
  web/src/Pages/Home.jsx
  web/src/img/amplify.png
  web/src/img/babel.png
  web/src/img/docsify.png
  web/src/img/mlh-logo-color.svg
  web/src/img/mlh.png
  web/src/img/n8n.png
  web/src/img/screenShot.png
  web/src/img/sheetjs.png
  web/src/img/webaverse.ico
  web/src/primer.css
Labels: webapp design, webapp functionality

#13 Add react-router for /events and /fellows pages
  web/package-lock.json
  web/package.json
  web/src/App.js
  web/src/Pages/Events.js
  web/src/Pages/Fellows.js
  web/src/Pages/Home.jsx
Labels: halfway-hackathon, webapp functionality

#32 Add jobs page, data and route
  web/src/App.js
  web/src/Pages/Jobs.js
  web/src/data/jobs.json
Labels: halfway-hackathon, webapp design, webapp functionality

#30 Add events web integration
  web/src/App.css
  web/src/App.js
  web/src/Components/Event.js
  web/src/Components/Header.jsx
  web/src/Components/TabPanel.js
  web/src/Components/index.js
  web/src/Pages/Events.js
  web/src/Pages/Home.jsx
Labels: halfway-hackathon

#33 Add to About page
  web/src/App.js
  web/src/Components/Header.jsx
  web/src/Pages/About.js
Labels: halfway-hackathon, webapp design

#35 Add Get Help page
  web/src/App.css
  web/src/App.js
  web/src/Components/Header.jsx
  web/src/Pages/GetHelp.js
  web/src/data/techs.json
Labels: halfway-hackathon, webapp design, webapp functionality

#39 Add portfolio page & other minor tweaks
  web/src/App.css
  web/src/App.js
  web/src/Components/Card.js
  web/src/Components/Event.js
  web/src/Components/Header.jsx
  web/src/Components/Projects.js
  web/src/Components/Search.js
  web/src/Components/SimpleAvatar.js
  web/src/Components/index.js
  web/src/Pages/About.js
  web/src/Pages/Fellows.js
  web/src/Pages/Home.jsx
  web/src/Pages/Jobs.js
  web/src/Pages/Portfolio.js
Labels: halfway-hackathon, webapp design, webapp functionality

#41 Templates section
  web/src/App.js
  web/src/Components/Header.jsx
  web/src/Components/index.js
  web/src/Pages/Templates.js
Labels: halfway-hackathon, webapp design, webapp functionality, writing task

#43 Add !mockme command to Discord bot
  discord-bot/commands/help.js
  discord-bot/commands/mockme.js
  discord-bot/commands/votefor.js
Labels: Discord bot, halfway-hackathon

#37 Voting contest section
  web/src/App.js
  web/src/Components/Header.jsx
  web/src/Pages/VotingContest.js
  web/src/img/book-promo.png
Labels: halfway-hackathon, webapp design, webapp functionality, writing task

#50 Podmates tab
  web/src/App.js
  web/src/Components/PodmateAvatar.js
  web/src/Components/index.js
  web/src/Pages/Home.jsx
Labels: halfway-hackathon, webapp design, webapp functionality

#52 Hook up search bar in topbar to pages with search functionality (& minor changes)
  web/src/App.css
  web/src/App.js
  web/src/Components/Header.jsx
  web/src/Components/Projects.js
  web/src/Pages/About.js
  web/src/Pages/Events.js
  web/src/Pages/GetHelp.js
  web/src/Pages/Home.jsx
  web/src/Pages/Jobs.js
  web/src/data/projects.json
  web/src/img/projects/AliceVision.png
  web/src/img/projects/HDI.png
  web/src/img/projects/Nextjs.png
  web/src/img/projects/amplify.png
  web/src/img/projects/babel.png
  web/src/img/projects/beagleBoard.png
  web/src/img/projects/bentoml.png
  web/src/img/projects/circuitPython.png
  web/src/img/projects/devto.png
  web/src/img/projects/docsify.png
  web/src/img/projects/docusaurus.png
  web/src/img/projects/fastApi.png
  web/src/img/projects/homebrew.png
  web/src/img/projects/httpie.jpg
  web/src/img/projects/index.js
  web/src/img/projects/jest.png
  web/src/img/projects/julia.svg
  web/src/img/projects/keras.png
  web/src/img/projects/n8n.png
  web/src/img/projects/ohmyzsh.png
  web/src/img/projects/pallets.png
  web/src/img/projects/react-jsonschema-form.png
  web/src/img/projects/react-native.png
  web/src/img/projects/react.png
  web/src/img/projects/relay.svg
  web/src/img/projects/scikit_learn.png
  web/src/img/projects/sciml.png
  web/src/img/projects/sheetjs.png
  web/src/img/projects/typer.svg
  web/src/img/projects/webaverse.ico
  web/src/img/projects/wfp.png
Labels: halfway-hackathon, webapp design, webapp functionality

#45 Add Exchange Network section to Portfolio
  aws-backend/amplify/backend/function/fellowendpoint/fellowendpoint-cloudformation-template.json
  aws-backend/amplify/backend/function/fellowendpoint/src/app.js
  aws-backend/amplify/backend/function/githubauthtoken/githubauthtoken-cloudformation-template.json
  aws-backend/amplify/backend/function/githubauthtoken/src/app.js
  web/src/App.css
  web/src/App.js
  web/src/Components/index.js
  web/src/Pages/GetHelp.js
  web/src/Pages/Home.jsx
  web/src/Pages/Portfolio.js
  web/src/data/linkedin-recommendation-templates.json
Labels: halfway-hackathon, webapp design, webapp functionality

#61 Fix web styling
  web/src/Components/Loading.js
  web/src/Components/Projects.js
  web/src/Pages/About.js
  web/src/Pages/Home.jsx
  web/src/Pages/Portfolio.js
  web/src/Pages/Templates.js
  web/src/data/projects.json
Labels: webapp design

#62 Final web fixes
  web/netlify.toml
  web/src/Pages/Home.jsx
  web/src/Pages/Portfolio.js
Labels: halfway-hackathon, webapp design, webapp functionality

#64 Optimise web API requests; Require login on most pages
  web/src/App.css
  web/src/App.js
  web/src/Components/Login.js
  web/src/Components/index.js
  web/src/Pages/Events.js
  web/src/Pages/Fellows.js
  web/src/Pages/GetHelp.js
  web/src/Pages/Home.jsx
  web/src/Pages/Jobs.js
  web/src/Pages/Portfolio.js
  web/src/Pages/Templates.js
  web/src/Pages/VotingContest.js
Labels: halfway-hackathon, webapp functionality
